apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: spring-boot
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: spring-boot
  replicas: 3 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
      - name: spring-boot
        image: gcr.io/umar-poc/springboot:latest
        ports:
        - containerPort: 8080
